Repository Cryptonomic/MonadicDNA, pull requests merged in 2024-04, with the labels that each got.

#6 Monadic dna UI
  monadic-dna-portal/.eslintrc.json
  monadic-dna-portal/.gitignore
  monadic-dna-portal/README.md
  monadic-dna-portal/next.config.mjs
  monadic-dna-portal/package-lock.json
  monadic-dna-portal/package.json
  monadic-dna-portal/postcss.config.js
  monadic-dna-portal/public/loading.svg
  monadic-dna-portal/public/upload.svg
  monadic-dna-portal/src/app/favicon.ico
  monadic-dna-portal/src/app/globals.css
  monadic-dna-portal/src/app/layout.tsx
  monadic-dna-portal/src/app/page.tsx
  monadic-dna-portal/src/app/passport/create/page.tsx
  monadic-dna-portal/src/components/downloadWallet.tsx
  monadic-dna-portal/src/components/header.tsx
  monadic-dna-portal/src/components/modal.tsx
  monadic-dna-portal/src/components/tabs.tsx
  monadic-dna-portal/src/components/uploadFile.tsx
  monadic-dna-portal/src/components/viewAttestations.tsx
  monadic-dna-portal/src/components/visuallyHiddenInput.tsx
  monadic-dna-portal/src/config.json
  monadic-dna-portal/src/lib/abi/SignProtocol.json
  monadic-dna-portal/src/react-app-env.d.ts
  monadic-dna-portal/src/theme.ts
  monadic-dna-portal/src/types/uploadFile.ts
  monadic-dna-portal/src/utils/attestations.ts
  monadic-dna-portal/src/utils/formatting.ts
  monadic-dna-portal/tailwind.config.ts
  monadic-dna-portal/tsconfig.json
  schema.json
Labels: enhancement

#9 Changed Nillion node ID generation and Nillion API port
  services/nillion-interactor/README.md
  services/nillion-interactor/app.py
  services/nillion-interactor/nadatest.py
Labels: bug

#17 mtDog landing page
  mtDog/web/Designer.png
  mtDog/web/index.html
Labels: enhancement

#18 Added CORS handling and changed Nillion node key generation
  services/nillion-interactor/app.py
  services/nillion-interactor/nadatest.py
  services/nillion-interactor/requirements.txt
Labels: bug

#22 snipper bot landing page
  snipper-bot/landing-page/global.css
  snipper-bot/landing-page/index.css
  snipper-bot/landing-page/index.html
  snipper-bot/landing-page/public/snipperbot-logo-1@2x.png
  snipper-bot/landing-page/public/snipperbot-logo-2-2@2x.png
  snipper-bot/landing-page/public/snipperbot-logo-21.svg
Labels: enhancement

#25 Ensuring the Sign Protocol API actually returns a result
  services/sign-protocol-interactor/README.md
  services/sign-protocol-interactor/src/app.ts
Labels: bug

#26 Added some GET routes for debugging the Sign Protocol service
  services/sign-protocol-interactor/src/app.ts
Labels: enhancement

#21 Monadic DNA Landing Page and Updated app UI
  monadic-dna-portal/package-lock.json
  monadic-dna-portal/package.json
  monadic-dna-portal/public/logo.png
  monadic-dna-portal/public/privacy.png
  monadic-dna-portal/src/app/layout.tsx
  monadic-dna-portal/src/app/page.tsx
  monadic-dna-portal/src/app/passport/[action]/page.tsx
  monadic-dna-portal/src/app/passport/page.tsx
  monadic-dna-portal/src/components/downloadWallet.tsx
  monadic-dna-portal/src/components/errorModal.tsx
  monadic-dna-portal/src/components/fileProgressDetails.tsx
  monadic-dna-portal/src/components/getExternalDataset.tsx
  monadic-dna-portal/src/components/header.tsx
  monadic-dna-portal/src/components/landingPage/footer.tsx
  monadic-dna-portal/src/components/landingPage/howItWorks.tsx
  monadic-dna-portal/src/components/landingPage/landingPageHeader.tsx
  monadic-dna-portal/src/components/landingPage/problemStatement.tsx
  monadic-dna-portal/src/components/landingPage/solution.tsx
  monadic-dna-portal/src/components/modal.tsx
  monadic-dna-portal/src/components/uploadFile.tsx
  monadic-dna-portal/src/components/viewAttestations.tsx
  monadic-dna-portal/src/components/viewResults.tsx
  monadic-dna-portal/src/config.json
  monadic-dna-portal/src/types/uploadFile.ts
  monadic-dna-portal/src/utils/attestations.ts
  monadic-dna-portal/src/utils/formatting.ts
  monadic-dna-portal/src/utils/index.ts
  monadic-dna-portal/src/utils/nillion.ts
  monadic-dna-portal/src/utils/signProtocol.ts
  snipper-bot/src/config.json
Labels: enhancement

#27 Switch to HTTPS Nillion API
  monadic-dna-portal/src/config.json
  snipper-bot/src/config.json
Labels: bug

#29 mtDog UI
  mtDog/lib/assets/blank.png
  mtDog/lib/assets/blue-tick.png
  mtDog/lib/assets/cpu.png
  mtDog/lib/assets/dna.png
  mtDog/lib/assets/green_tick.png
  mtDog/lib/assets/grey_tick.png
  mtDog/lib/assets/icon.png
  mtDog/lib/assets/passport.png
  mtDog/lib/assets/readme.md
  mtDog/lib/assets/upload.png
  mtDog/lib/host/src/app.rs
  mtDog/lib/host/src/app/common.rs
  mtDog/lib/host/src/app/diabetes.rs
  mtDog/lib/host/src/app/prover.rs
  mtDog/lib/host/src/lib.rs
  mtDog/lib/host/src/main.rs
  mtDog/lib/methods/guest/src/common.rs
  mtDog/lib/methods/guest/src/main.rs
Labels: enhancement

#30 Missing toml for mtDog
  mtDog/lib/host/Cargo.toml
Labels: bug

#33 Fixed bug with the way params were being read in the Sign Protocol API
  services/sign-protocol-interactor/src/app.ts
Labels: bug

#34 mtDog: Set correct http header
  mtDog/lib/host/src/app.rs
Labels: bug

#35 snipper-bot ui
  monadic-dna-portal/public/logo.png
  monadic-dna-portal/public/logo.svg
  monadic-dna-portal/public/privacy.png
  monadic-dna-portal/public/privacy.svg
  monadic-dna-portal/src/app/layout.tsx
  monadic-dna-portal/src/components/errorModal.tsx
  monadic-dna-portal/src/components/header.tsx
  monadic-dna-portal/src/components/landingPage/footer.tsx
  monadic-dna-portal/src/components/landingPage/problemStatement.tsx
  monadic-dna-portal/src/components/viewResults.tsx
  snipper-bot/public/logo.svg
  snipper-bot/src/app/layout.tsx
  snipper-bot/src/components/analysisInsights.tsx
  snipper-bot/src/components/analysisStepper.tsx
  snipper-bot/src/components/errorModal.tsx
  snipper-bot/src/components/fileProgressIndicator.tsx
  snipper-bot/src/components/header.tsx
  snipper-bot/src/components/uploadFile.tsx
  snipper-bot/src/components/viewAttestations.tsx
  snipper-bot/src/config.json
  snipper-bot/src/theme.ts
  snipper-bot/src/types/customError.ts
  snipper-bot/src/utils/attestations.ts
  snipper-bot/src/utils/formatting.ts
  snipper-bot/src/utils/index.ts
  snipper-bot/src/utils/nillion.ts
Labels: enhancement

#36 Made Sign Protocol API compatible with DO builds
  services/sign-protocol-interactor/README.md
  services/sign-protocol-interactor/src/app.ts
Labels: bug

#39 Added linux build link to the mt-dog landing page
  mtDog/web/index.html
Labels: enhancement

#41 Added Mac build link
  mtDog/web/index.html
Labels: enhancement

#44 link snipper bot route
  snipper-bot/landing-page/index.css
  snipper-bot/landing-page/index.html
Labels: bug

#45 Update Monadic UI
  monadic-dna-portal/src/components/fileProgressDetails.tsx
  monadic-dna-portal/src/components/uploadFile.tsx
  monadic-dna-portal/src/components/viewResults.tsx
  monadic-dna-portal/src/config.json
  monadic-dna-portal/src/utils/signProtocol.ts
Labels: bug

#47 Fix/attestation results 2
  monadic-dna-portal/src/components/uploadFile.tsx
  monadic-dna-portal/src/components/viewResults.tsx
  monadic-dna-portal/src/utils/index.ts
  monadic-dna-portal/src/utils/signProtocol.ts
Labels: enhancement

#24 Nada additions and fixes, docs and logging in general for Nillion
  services/nillion-interactor/.env
  services/nillion-interactor/README.md
  services/nillion-interactor/binaries/muscle-perform.nada.bin
  services/nillion-interactor/binaries/muscle-perform.nada.json
  services/nillion-interactor/binaries/thrombosis.nada.bin
  services/nillion-interactor/binaries/thrombosis.nada.json
  services/nillion-interactor/compile.sh
  services/nillion-interactor/nadatest.py
  services/nillion-interactor/programs/muscle-perform.py
  services/nillion-interactor/programs/thrombosis.py
  services/nillion-interactor/store_program.sh
Labels: enhancement

#52 added instructions to install risc zero
  mtDog/web/index.html
Labels: enhancement

#54 renamed file
  monadic-dna-portal/src/components/downloadWallet.tsx
  monadic-dna-portal/src/components/passportContent.tsx
Labels: bug

#55 Fix/create attestation
  snipper-bot/src/components/uploadFile.tsx
Labels: bug

#56 Filter providers
  snipper-bot/src/components/uploadFile.tsx
  snipper-bot/src/config.json
Labels: enhancement

#57 Expand READMEs and add an additional instruction of the mtDog landing page
  README.md
  mtDog/web/index.html
  snipper-bot/README.md
Labels: documentation

#61 Remove attestation delay
  snipper-bot/src/components/uploadFile.tsx
  snipper-bot/src/utils/attestations.ts
Labels: enhancement

#60 Fix File Progress State on Firefox
  monadic-dna-portal/src/components/fileProgressDetails.tsx
  monadic-dna-portal/src/components/uploadFile.tsx
  monadic-dna-portal/src/types/uploadFile.ts
  monadic-dna-portal/src/utils/index.ts
  snipper-bot/src/components/fileProgressIndicator.tsx
  snipper-bot/src/components/uploadFile.tsx
  snipper-bot/src/utils/index.ts
Labels: enhancement

#62 add link to privacy tools
  monadic-dna-portal/src/components/landingPage/howItWorks.tsx
Labels: enhancement
